import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Bebas_Neue } from "next/font/google";
import "./globals.css";


// const bebasNeue = Bebas_Neue({
//   variable: "--font-bebas-beue",
//   weight: "400",
//   subsets: ["latin"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto px-4">
          <div className="grid grid-cols-1 sm:flex sm:flex-wrap sm:justify-between gap-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
